In [1]:
import numpy as np
import open3d as o3d



In [2]:

# Step 1: Define an arbitrary rotation axis (e.g., rotate around the x-axis)
arbitrary_axis = np.array([1.0, 0.5, 0.8])  # x-axis

# Step 2: Define an arbitrary rotation angle (e.g., 90 degrees)
angle_degrees = 90
angle_radians = np.radians(angle_degrees)  # Convert degrees to radians

# Step 3: Normalize the arbitrary axis
arbitrary_axis_normalized = arbitrary_axis / np.linalg.norm(arbitrary_axis)
print(f"Arbitrary Axis (normalized): {arbitrary_axis_normalized}")
magnitude = np.linalg.norm(arbitrary_axis_normalized)
print(f"Magnitude: {magnitude}")

# Step 4: Compute the axis-angle representation (axis * angle)
axis_angle = arbitrary_axis_normalized * angle_radians
print(f"Arbitrary Axis-Angle Representation: {axis_angle}")



# Step 6: Apply the rotation to a point cloud (assuming 'pcd' is already defined)

Arbitrary Axis (normalized): [0.72739297 0.36369648 0.58191437]
Magnitude: 1.0
Arbitrary Axis-Angle Representation: [1.1425862  0.5712931  0.91406896]


In [3]:
# Step 5: Compute the rotation matrix from the axis-angle representation
rotation_matrix = o3d.geometry.get_rotation_matrix_from_axis_angle(axis_angle)
print(f"Rotation Matrix (arbitrary):\n{rotation_matrix}")

Rotation Matrix (arbitrary):
[[ 0.52910053 -0.31736411  0.78697691]
 [ 0.84646464  0.13227513 -0.51575276]
 [ 0.05958394  0.93903318  0.33862434]]
